/**
 * Composition Intermediate Representation (IR)
 *
 * This defines the core data structure for video compositions in ChatKut.
 * The IR is the single source of truth that gets converted to Remotion code.
 */

// Main composition structure
export type CompositionIR = {
  id: string;
  version: number;
  metadata: CompositionMetadata;
  elements: CompositionElement[];
  patches: Patch[]; // For undo/redo
};

// Composition metadata
export type CompositionMetadata = {
  width: number; // e.g., 1920
  height: number; // e.g., 1080
  fps: number; // e.g., 30
  durationInFrames: number; // e.g., 300 for 10 seconds at 30fps
};

// Base element type
export type CompositionElement = {
  id: string; // Stable ID for selectors
  type: ElementType;
  label?: string; // User-defined or AI-generated label
  from: number; // Start frame
  durationInFrames: number;
  properties: Record<string, any>; // Element-specific properties
  animations?: Animation[];
  children?: CompositionElement[]; // For sequences
};

// Element types
export type ElementType = "video" | "audio" | "text" | "image" | "sequence" | "shape";

// Video element properties
export type VideoElementProperties = {
  src: string; // Asset URL (Cloudflare Stream HLS or R2)
  volume?: number; // 0-1
  playbackRate?: number; // Speed multiplier
  startFrom?: number; // Start offset in frames
  endAt?: number; // End offset in frames
};

// Audio element properties
export type AudioElementProperties = {
  src: string; // Asset URL
  volume?: number; // 0-1
  playbackRate?: number;
  startFrom?: number;
  endAt?: number;
};

// Text element properties
export type TextElementProperties = {
  text: string;
  fontFamily?: string;
  fontSize?: number;
  fontWeight?: string | number;
  color?: string;
  backgroundColor?: string;
  textAlign?: "left" | "center" | "right";
  x?: number; // Position X (pixels or percentage)
  y?: number; // Position Y
  width?: number;
  height?: number;
  padding?: number;
  borderRadius?: number;
};

// Image element properties
export type ImageElementProperties = {
  src: string; // Asset URL (Cloudflare R2)
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  fit?: "cover" | "contain" | "fill" | "none";
  opacity?: number;
};

// Sequence element (container for other elements)
export type SequenceElementProperties = {
  // Sequences don't have their own properties beyond children
};

// Animation definition
export type Animation = {
  property: string; // e.g., "opacity", "scale", "x", "y", "rotate"
  keyframes: Keyframe[];
  easing?: EasingType;
};

// Keyframe for animations
export type Keyframe = {
  frame: number; // Absolute frame number
  value: any; // Value at this frame
};

// Easing types (maps to Remotion interpolate options)
export type EasingType =
  | "linear"
  | "ease-in"
  | "ease-out"
  | "ease-in-out"
  | "spring";

// Patch for undo/redo
export type Patch = {
  id: string;
  timestamp: number;
  operation: PatchOperation;
  selector: ElementSelector;
  changes: any; // Operation-specific changes
  previousState?: any; // For undo
};

// Patch operations
export type PatchOperation = "add" | "update" | "delete" | "move";

// Element selectors (how to find elements in the IR)
export type ElementSelector =
  | ByIdSelector
  | ByLabelSelector
  | ByIndexSelector
  | ByTypeSelector;

export type ByIdSelector = {
  type: "byId";
  id: string;
};

export type ByLabelSelector = {
  type: "byLabel";
  label: string;
};

export type ByIndexSelector = {
  type: "byIndex";
  index: number;
};

export type ByTypeSelector = {
  type: "byType";
  elementType: ElementType;
  index?: number; // Optional: e.g., "second video clip"
};

// Edit Plan (generated by LLM)
export type EditPlan = {
  operation: PatchOperation;
  selector: ElementSelector;
  changes: any;
  reasoning?: string; // Optional: why this plan was generated
};

// Execution result
export type ExecutionResult =
  | SuccessResult
  | AmbiguousResult
  | ErrorResult;

export type SuccessResult = {
  status: "success";
  updatedIR: CompositionIR;
  newCode: string;
  patch: Patch;
  receipt: string; // User-friendly message
};

export type AmbiguousResult = {
  status: "ambiguous";
  candidates: ElementCandidate[];
};

export type ErrorResult = {
  status: "error";
  errors: string[];
  suggestedFixes?: string[];
};

// Element candidate (for disambiguation)
export type ElementCandidate = {
  id: string;
  label?: string;
  thumbnail?: string; // Base64 or URL
  timecode: string; // e.g., "0:05"
  element: CompositionElement;
};

// Helper type guards
export function isVideoElement(
  element: CompositionElement
): element is CompositionElement & { properties: VideoElementProperties } {
  return element.type === "video";
}

export function isAudioElement(
  element: CompositionElement
): element is CompositionElement & { properties: AudioElementProperties } {
  return element.type === "audio";
}

export function isTextElement(
  element: CompositionElement
): element is CompositionElement & { properties: TextElementProperties } {
  return element.type === "text";
}

export function isImageElement(
  element: CompositionElement
): element is CompositionElement & { properties: ImageElementProperties } {
  return element.type === "image";
}

export function isSequenceElement(
  element: CompositionElement
): element is CompositionElement & { properties: SequenceElementProperties } {
  return element.type === "sequence";
}
